feat: adding github action for edocs preview
empathyco/platform-reusable-github-actions pull request #1
Opened 2022-11-14 16:32 UTC by PedroOndh

Good afternoon! 

We have created and tested this Github action that receiving a repository, branch and PR number will create a preview with those changes and publish a comment in the given PR. 😄

After merging this our next step would be to connect this with X team, we already did a test in [this closed PR](https://github.com/empathyco/x/pull/849).

Please comment us any possible improvement you see. 🙏

2022-11-14 17:21 UTC, guillermotti requested changes

2022-11-14 17:21 UTC, guillermotti commented on .github/workflows/edocs-preview.yml
> +        required: true
I think you should add here the type, otherwise it will fail

2022-11-14 17:21 UTC, guillermotti commented on .github/workflows/edocs-preview.yml
> +        required: true
Same here

2022-11-14 17:21 UTC, guillermotti commented on .github/workflows/edocs-preview.yml
> +        required: true
Same here

2022-11-14 17:21 UTC, guillermotti commented on .github/workflows/edocs-preview.yml
> +        default: ''
And here

2022-11-15 08:07 UTC, carmen279 commented on .github/workflows/edocs-preview.yml
> +        required: true
Done ✅

2022-11-15 08:07 UTC, carmen279 commented on .github/workflows/edocs-preview.yml
> +        required: true
Done ✅

2022-11-15 08:07 UTC, carmen279 commented on .github/workflows/edocs-preview.yml
> +        required: true
Done ✅

2022-11-15 08:08 UTC, carmen279 commented on .github/workflows/edocs-preview.yml
> +        default: ''
Done ✅

2022-11-15 08:20 UTC, guillermotti approved these changes

2022-11-15 08:27 UTC, merged